name: markus

description: "An interactive multilingual voice assistant and digital security"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.30.0
  animated_toggle_switch: ^0.8.2
  iconsax: ^0.0.8
  speech_to_text: ^6.6.1
  avatar_glow: ^3.0.1
  highlight_text: ^1.7.0
  camera: ^0.10.5+9
  video_player: ^2.8.6
  firebase_storage: ^11.7.2
  google_gemini: ^0.1.2
  image_picker: ^1.1.0
  translator: ^1.0.0
  flutter_tts: ^4.0.2
  http: ^1.2.1
  chewie: ^1.8.1
  cloud_firestore: ^4.17.2
  firebase_messaging: ^14.9.1
  google_generative_ai: ^0.3.2


flutter:
  uses-material-design: true
  assets:
    - assets/crime.png
    - assets/fire.png
    - assets/gas_leak.png
































